'update'

diff --git a/.github/workflows/my_workflow.yml b/.github/workflows/my_workflow.yml
--- a/.github/workflows/my_workflow.yml
+++ b/.github/workflows/my_workflow.yml
@@ -1,6 +1,9 @@
 concurrency:
   cancel-in-progress: true
   group: pages
+defaults:
+  run:
+    shell: bash
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -9,15 +12,47 @@ jobs:
       uses: actions/checkout@v3
     - name: list directory
       run: ls -lR
-    - name: Setup Pages
-      uses: actions/configure-pages@v2
-    - name: Build with Jekyll
-      uses: actions/jekyll-build-pages@v1
+    - id: detect-package-manager
+      name: Detect package manager
+      run: "if [ -f \"${{ github.workspace }}/yarn.lock\" ]; then\n  echo \"manager=yarn\"\
+        \ >> $GITHUB_OUTPUT\n  echo \"command=install\" >> $GITHUB_OUTPUT\n  exit\
+        \ 0\nelif [ -f \"${{ github.workspace }}/package.json\" ]; then\n  echo \"\
+        manager=npm\" >> $GITHUB_OUTPUT\n  echo \"command=ci\" >> $GITHUB_OUTPUT\n\
+        \  exit 0\nelse\n  echo \"Unable to determine packager manager\"\n  exit 1\n\
+        fi\n"
+    - name: Setup Node
+      uses: actions/setup-node@v3
       with:
-        destination: ./_site
-        source: ./
+        cache: ${{ steps.detect-package-manager.outputs.manager }}
+        node-version: '18'
+    - id: pages
+      name: Setup Pages
+      uses: actions/configure-pages@v2
+      with:
+        static_site_generator: gatsby
+    - name: Restore cache
+      uses: actions/cache@v3
+      with:
+        key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
+        path: 'public
+
+          .cache
+
+          '
+        restore-keys: '${{ runner.os }}-gatsby-build-
+
+          '
+    - name: Install dependencies
+      run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command
+        }}
+    - env:
+        PREFIX_PATHS: 'true'
+      name: Build with Gatsby
+      run: ${{ steps.detect-package-manager.outputs.manager }} run build
     - name: Upload artifact
       uses: actions/upload-pages-artifact@v1
+      with:
+        path: ./public
   deploy:
     environment:
       name: github-pages
@@ -28,11 +63,11 @@ jobs:
     - id: deployment
       name: Deploy to GitHub Pages
       uses: actions/deploy-pages@v1
-name: Deploy Jekyll with GitHub Pages dependencies preinstalled
+name: Deploy Gatsby site to Pages
 'on':
   push:
     branches:
-    - main
+    - $default-branch
   workflow_dispatch: null
 permissions:
   contents: read
